name: github-com_kasaikou
services:
  dev:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - apt_mirror=${APT_MIRROR:-archive.ubuntu.com}
        - username=${USER}
        - uid=${UID}
        - gid=${GID}
    command: sh /run.sh
    privileged: true
    tty: true
    user: ${USER}
    volumes:
      - src:/workspace
      - ${WORKSPACE_DIR}:${WORKSPACE_DIR}
      - ../.config/fish/:/home/${USER}/.config/fish/
      - ../.bashrc:/home/${USER}/.bashrc
      - /run/user/${UID}/gnupg:/run/user/${UID}/gnupg
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    env_file:
      - .env
volumes:
  src:
