ARG username=vscode
ARG useruid=1000
ARG usergid=1000
ARG apt_mirror=archive.ubuntu.com

FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=nointeractive
ARG apt_mirror

RUN sed -i "s@archive.ubuntu.com@${apt_mirror}@g" /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends \
    sudo=1.9.9-1ubuntu2.4 \
    wget=1.21.2-2ubuntu1 \
    curl=7.81.0-1ubuntu1.14 \
    git=1:2.34.1-1ubuntu1.10 \
    unzip=6.0-26ubuntu3.1 \
    ca-certificates=20230311ubuntu0.22.04.1 \
    gnupg=2.2.27-3ubuntu2.1 \
    apt-transport-https=2.4.10 \
    software-properties-common=0.99.22.8 \
    build-essential=12.9ubuntu3 \
    # for chrome-browser
    libglib2.0-0=2.72.4-0ubuntu2.2 \
    libnss3=2:3.68.2-0ubuntu1.2 \
    libatk1.0-0=2.36.0-3build1 \
    libatk-bridge2.0-0=2.38.0-3 \
    libcups2=2.4.1op1-1ubuntu4.7 \
    libdrm2=2.4.113-2~ubuntu0.22.04.1 \
    libxkbcommon0=1.4.0-1 \
    libxcomposite1=1:0.4.5-1build2 \
    libxdamage1=1:1.1.5-2build2 \
    libxfixes3=1:6.0.0-1 \
    libxrandr2=2:1.5.2-1build1 \
    libgbm1=23.0.4-0ubuntu1~22.04.1 \
    libpango-1.0-0=1.50.6+ds-2ubuntu1 \
    libcairo2=1.16.0-5ubuntu2 \
    libasound2=1.2.6.1-1ubuntu1 \
    fonts-ipaexfont-mincho=00401-3ubuntu1 \
    poppler-utils=22.02.0-2ubuntu0.3 \
    ghostscript=9.55.0~dfsg1-0ubuntu5.5 \
    php-common=2:92ubuntu1 \
    php-cli=2:8.1+92ubuntu1

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb && \
    dpkg -i cuda-keyring_1.0-1_all.deb && \
    apt-get update && \
    apt-get -y install libcutensor1 libcutensor-dev libcutensor-doc libcudnn8-dev

# Docker and Compose (for DooD)
# hadolint ignore=DL3009
RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo deb "[arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y --no-install-recommends docker-ce-cli=5:24.0.6-1~ubuntu.22.04~jammy && \
    mkdir -p /usr/local/lib/docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose && \
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

# PHP
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');"

# fish
RUN apt-add-repository ppa:fish-shell/release-3 && \
    apt-get update && apt-get install -y --no-install-recommends fish=3.6.1-1~jammy

# Go
ARG go=1.21.3
RUN wget -O go.tar.gz https://go.dev/dl/go${go}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go.tar.gz && \
    rm -rf go.tar.gz
ENV PATH=${PATH}:/usr/local/go/bin

# act
RUN curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | bash

# Node and Yarn
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | \
    tee /etc/apt/sources.list.d/nodesource.list > /dev/null && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && \
    sudo apt-get update && sudo apt-get install -y --no-install-recommends nodejs=18.18.2-1nodesource1 yarn=1.22.19-1

RUN yarn global add press-ready

ARG username
ARG useruid
ARG usergid

RUN groupadd --gid ${usergid} ${username} && \
    useradd -s /bin/bash --uid ${useruid} --gid ${usergid} -m ${username} && \
    echo ${username} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${username} && \
    chmod 0440 /etc/sudoers.d/${username}

COPY ./run.sh /

USER ${username}
ENV PATH=${PATH}:/home/${username}/go/bin

# Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
ENV PATH=${PATH}:/home/${username}/.local/bin
